accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
  path('signup/', views.signup, name='signup'),
  path('profile/', views.profile, name='profile'),
  path('profile/edit/', views.edit_profile, name='edit_profile'),
]

jobs/urls.py
from django.urls import path
from . import views

app_name = 'jobs'

urlpatterns = [
  path('', views.jobs, name='jobs'),
  path('<int:id>/', views.job, name='job'),
  path('add-job/', views.add_job, name='add_job'),
  path('add-category/', views.add_category, name='add_category'),
  path('job-orders/', views.job_orders, name='job_orders'),
  path('delete/<int:id>/', views.delete_job, name='delete_job'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('jobs.urls', namespace='jobs')),
]
urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User

class Profile(models.Model):
  gender = {
    ('male','male'),
    ('female','female'),
  }
  user = models.OneToOneField(User, on_delete=models.CASCADE, default='not found')
  job = models.CharField(max_length=100, default='not found')
  address = models.CharField(max_length=100, default='not found')
  phone_number = models.CharField(max_length=12, default='not found')
  gender = models.CharField(max_length=100, choices=gender, default='not found')
  image = models.ImageField(upload_to='profiles/')
  
  def __str__(self):
    return str(self.user)
  
  @receiver(post_save, sender = User)
  def create_user_profile(sender, instance, created, **kwargs):
    if created: 
      Profile.objects.create(user = instance)

jobs/models.py
from django.db import models
from accounts.models import Profile

class Job(models.Model):
  job_type = {
    ('Part-time', 'Part-time'),
    ('Full-time', 'Full-time')
  }
  job_title = models.CharField(max_length=100)
  job_type = models.CharField(max_length=100, choices=job_type)
  job_salary = models.DecimalField(max_digits=6, decimal_places=2)
  job_vacancy = models.IntegerField()
  job_category = models.ForeignKey("Category", on_delete=models.CASCADE)
  job_description = models.TextField(max_length=300)
  job_location = models.CharField(max_length=100)
  job_image = models.ImageField(upload_to='jobs/')
  created_at = models.DateTimeField(auto_now=True)
  
  def __str__(self):
    return self.job_title


class Category(models.Model):
  category_name = models.CharField(max_length=100)
  
  class Meta:
    verbose_name = ("Category")
    verbose_name_plural = ("Categories")
  
  def __str__(self):
    return self.category_name


class JobOrder(models.Model):
  profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
  job = models.ForeignKey("Job", on_delete=models.CASCADE)
  cv = models.FileField(upload_to='cv/')
  website_link = models.URLField()
  cover_letter = models.TextField(max_length=300)
  created_at = models.DateTimeField(auto_now=True)
  
  def __str__(self):
    return self.name

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
  class Meta:
    model = User
    fields = ['username', 'email', 'password1', 'password2', 'is_superuser']


class UserForm(forms.ModelForm):
  class Meta:
    model = User
    fields = ['username', 'email', 'first_name', 'last_name']


class ProfileForm(forms.ModelForm):
  class Meta:
    model = Profile
    fields = ['job', 'address', 'phone_number', 'gender', 'image']

jobs/forms.py
from django import forms
from .models import JobOrder, Job, Category

class JobForm(forms.ModelForm):
  class Meta:
    model = Job
    fields = ['job_title', 'job_type', 'job_salary', 'job_vacancy', 'job_category', 'job_description', 'job_location', 'job_image']


class CategoryForm(forms.ModelForm):
  class Meta:
    model = Category
    fields = '__all__'


class JobOrderForm(forms.ModelForm):
  class Meta:
    model = JobOrder
    fields = ['cv', 'website_link', 'cover_letter']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from .forms import SignupForm, UserForm, ProfileForm
from .models import Profile

def signup(request):
  if request.method == 'POST':
    form = SignupForm(request.POST)
    if form.is_valid():
      form.save()
      username = form.cleaned_data['username']
      password = form.cleaned_data['password1']
      user = authenticate(username = username, password = password)
      login(request, user)
      return redirect('/accounts/profile') 
  else:
    form = SignupForm()
  return render(request, 'registration/signup.html', {'form': form})


@login_required(login_url='login')
def profile(request):
  profile = Profile.objects.get(user = request.user)
  return render(request, 'profile/profile.html', {'profile': profile})


@login_required(login_url='login')
def edit_profile(request):
  profile = Profile.objects.get(user = request.user)
  if request.method == 'POST':
    user_form = UserForm(request.POST, instance = request.user)
    profile_form = ProfileForm(request.POST, request.FILES, instance = profile)
    if user_form.is_valid and profile_form.is_valid():
      user_form.save()
      myform = profile_form.save(commit = False)
      myform.user = request.user
      myform.save()
      return redirect('/accounts/profile')
  else:
    user_form = UserForm(instance = request.user)
    profile_form = ProfileForm(instance = profile)
  return render(request, 'profile/edit_profile.html', {'user_form': user_form, 'profile_form': profile_form})

jobs/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from .forms import JobForm, CategoryForm, JobOrderForm
from accounts.models import Profile
from .models import Job, JobOrder

@login_required(login_url='login')
def jobs(request):
  jobs = Job.objects.all()
  jobs_count = Job.objects.all().count()
  
  paginator = Paginator(jobs, 3)
  page_number = request.GET.get('page')
  page_obj = paginator.get_page(page_number)
  
  context = {'jobs': page_obj, 'jobs_count': jobs_count}
  return render(request, 'jobs/jobs.html', context)


@login_required(login_url='login')
def job(request, id):
  job = Job.objects.get(id = id)
  profile = Profile.objects.get(user = request.user)
  if request.method == 'POST':
    form = JobOrderForm(request.POST, request.FILES)
    if form.is_valid():
      myform = form.save(commit=False)
      myform.job = job
      myform.profile = profile
      myform.save()
  else:
    form = JobOrderForm()
  return render(request, 'jobs/job.html', {'job': job, 'form': form})


@login_required(login_url='login')
def add_job(request):
  if request.method == 'POST':
    form = JobForm(request.POST, request.FILES)
    if form.is_valid():
      form.save()
      return redirect('/')
  else:
    form = JobForm()
  return render(request, 'jobs/add_job.html', {'form': form})


def delete_job(request, id):
  delete_category = Job.objects.get(id = id)
  delete_category.delete()
  return redirect('/')


@login_required(login_url='login')
def add_category(request):
  if request.method == 'POST':
    form = CategoryForm(request.POST, request.FILES)
    if form.is_valid():
      form.save()
      return redirect('/')
  else:
    form = CategoryForm()
  return render(request, 'jobs/add_category.html', {'form': form})


@login_required(login_url='login')
def job_orders(request):
  job_orders = JobOrder.objects.all()
  return render(request, 'jobs/job_orders.html', {'job_orders': job_orders})

accounts/templates/profile/edit_profile.html
{% extends "base.html" %}
{% block content %}
{% load bootstrap4 %}
<div class="bradcam_area bradcam_bg_1">
  <div class="container">
    <div class="row">
      <div class="col-xl-12">
        <div class="bradcam_text">
          <h3>Edit Profile</h3>
        </div>
      </div>
    </div>
  </div>
</div>
<div style="padding-top: 50px; padding-bottom: 70px">
  <div class="container">
    <div class="main-body">
      <div class="row gutters-sm">
        <div class="col-md-8 mx-auto">
          <div class="card">
            <div class="card-body">
              <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form user_form %}
                {% bootstrap_form profile_form %}
                <div class="row">
                  <div class="col-sm-12">
                    <input class="col btn main-btn" type="submit" value="Edit Profile">
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

accounts/templates/profile/profile.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<div class="bradcam_area bradcam_bg_1">
  <div class="container">
    <div class="row">
      <div class="col-xl-12">
        <div class="bradcam_text">
          <h3>My Profile</h3>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="" style="padding-top: 50px; padding-bottom: 70px">
  <div class="container">
    <div class="main-body">
      <div class="row gutters-sm">
        <div class="col-md-4 mb-3">
          <div class="card">
            <div class="card-body">
              <div class="d-flex flex-column align-items-center text-center">
                {% if profile.image %}
                <img src="{{profile.image.url}}" class="rounded-circle" width="150">
                {% else %}
                <img src="{% static 'images/default_img.png' %}" class="rounded-circle" width="150">
                {% endif %}
                <div class="mt-3">
                  <h4>{% if profile.user.first_name or profile.user.last_name %} {{profile.user.first_name}} {{profile.user.last_name}} {% else %} not found {% endif %}</h4>
                  <p class="text-secondary mb-1">{{profile.job}}</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-8">
          <div class="card mb-3">
            <div class="card-body">
              <div class="row">
                <div class="col-sm-3">
                  <h6 class="mb-0">Full Name</h6>
                </div>
                <div class="col-sm-9 text-secondary">
                  {% if profile.user.first_name or profile.user.last_name %} {{profile.user.first_name}} {{profile.user.last_name}} {% else %} not found {% endif %}
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <h6 class="mb-0">Username</h6>
                </div>
                <div class="col-sm-9 text-secondary">
                  {{profile.user}}
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <h6 class="mb-0">Email</h6>
                </div>
                <div class="col-sm-9 text-secondary">
                  {{profile.user.email}}
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <h6 class="mb-0">Phone</h6>
                </div>
                <div class="col-sm-9 text-secondary">
                  {{profile.phone_number}}
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <h6 class="mb-0">Gender</h6>
                </div>
                <div class="col-sm-9 text-secondary">
                  {{profile.gender}}
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <h6 class="mb-0">Profile type</h6>
                </div>
                <div class="col-sm-9 text-secondary">
                  {% if profile.user.is_superuser == True %} Hiring {% else %} Freelance {% endif %}
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <h6 class="mb-0">Address</h6>
                </div>
                <div class="col-sm-9 text-secondary">
                  {{profile.address}}
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-12">
                  <a href="{% url 'accounts:edit_profile' %}" class="col btn main-btn">Edit Profile</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

jobs/templates/jobs/add_category.html
{% extends "base.html" %}
{% block content %}
{% load static %}
{% load bootstrap4 %}
{% if user.is_superuser %}
<div class="bradcam_area bradcam_bg_1">
  <div class="container">
    <div class="row">
      <div class="col-xl-12">
        <div class="bradcam_text">
          <h3>Add Category</h3>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="" style="padding-top: 50px; padding-bottom: 70px">
  <div class="container">
    <div class="main-body">
      <div class="row gutters-sm">
        <div class="col-md-8 mx-auto">
          <div class="card mb-3">
            <div class="card-body">
              <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="row">
                  <div class="col-sm-12">
                    <input class="btn main-btn" type="submit" value="Add Category">
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endif %}
{% endblock content %}

jobs/templates/jobs/add_job.html
{% extends "base.html" %}
{% block content %}
{% load static %}
{% load bootstrap4 %}
{% if user.is_superuser %}
<div class="bradcam_area bradcam_bg_1">
  <div class="container">
    <div class="row">
      <div class="col-xl-12">
        <div class="bradcam_text">
          <h3>Add Job</h3>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="" style="padding-top: 50px; padding-bottom: 70px">
  <div class="container">
    <div class="main-body">
      <div class="row gutters-sm">
        <div class="col-md-8 mx-auto">
          <div class="card mb-3">
            <div class="card-body">
              <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="row">
                  <div class="col-sm-12">
                    <input class="btn main-btn" type="submit" value="Add Job">
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endif %}
{% endblock content %}

jobs/templates/jobs/job.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% load bootstrap4 %}
<div class="bradcam_area bradcam_bg_1">
  <div class="container">
    <div class="row">
      <div class="col-xl-12">
        <div class="bradcam_text">
          <h3>{{job.job_category}}</h3>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="job_details_area">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <div class="job_details_header">
          <div class="single_jobs white-bg d-flex justify-content-between">
            <div class="jobs_left d-flex align-items-center">
              <div class="thumb">
                {% if job.job_image %}
                <img src="{{job.job_image.url}}" alt="" width="60px" />
                {% else %}
                <img src="{% static 'images/default_img.png' %}" alt="" />
                {% endif %}
              </div>
              <div class="jobs_conetent">
                <a href=""><h4>{{job.job_title}}</h4></a>
                <div class="links_locat d-flex align-items-center">
                  <div class="location">
                    <p><i class="fa fa-map-marker"></i> {{job.job_location}}</p>
                  </div>
                  <div class="location">
                    <p><i class="fa fa-clock-o"></i> {{job.job_type}}</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="descript_wrap white-bg">
          <div class="single_wrap">
            <h4>Job description</h4>
            <p>
              {{job.job_description}}
            </p>
          </div>
        </div>
        {% if user.is_superuser %}
        {% else %}
        <div class="apply_job_form white-bg">
          <h4 style="padding-bottom: 20px">Apply for the job</h4>
          <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class="col-md-12">
              <div class="submit_btn">
                <button class="main-btn w-100" type="submit">Apply Now</button>
              </div>
            </div>
          </form>
        </div>
        {% endif %}
      </div>
      <div class="col-lg-4">
        <div class="job_sumary">
          <div class="summery_header">
            <h3>Job Summery</h3>
          </div>
          <div class="job_content">
            <ul>
              <li>Vacancy: <span>{{job.job_vacancy}}</span></li>
              <li>Salary: <span>${{job.job_salary}}</span></li>
              <li>Location: <span>{{job.job_location}}</span></li>
              <li>Job Type: <span> {{job.job_type}}</span></li>
              <li>Published on: <span>{{job.created_at|date:"d M, Y"}}</span></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

jobs/templates/jobs/job_orders.html
{% extends "base.html" %}
{% block content %}
{% load static %}
{% load bootstrap4 %}
{% if user.is_superuser %}
<div class="bradcam_area bradcam_bg_1">
  <div class="container">
    <div class="row">
      <div class="col-xl-12">
        <div class="bradcam_text">
          <h3>Job Orders</h3>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="" style="padding-top: 50px; padding-bottom: 70px">
  <div class="container">
    <div class="main-body">
      <div class="row">
        <table class="col table table-striped">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Job Order</th>
              <th scope="col">Profile</th>
              <th scope="col">Email</th>
              <th scope="col">Phone</th>
              <th scope="col">Address</th>
              <th scope="col">Website</th>
              <th scope="col">CV</th>
            </tr>
          </thead>
          <tbody>
            {% for job_order in job_orders %}
            <tr>
              <th scope="row">{{job_order.id}}</th>
              <td>{{job_order.job}}</td>
              <td>{% if job_order.profile.user.first_name or job_order.profile.user.last_name %} {{job_order.profile.user.first_name}} {{job_order.profile.user.last_name}} {% else %} not found {% endif %}</td>
              <td>{{job_order.profile.user.email}}</td>
              <td>{{job_order.profile.phone_number}}</td>
              <td>{{job_order.profile.address}}</td>
              <td>{{job_order.website_link}}</td>
              <td><a href="{{ job_order.cv.url }}">show cv</a></td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endif %}
{% endblock content %}

jobs/templates/jobs/jobs.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="bradcam_area bradcam_bg_1">
  <div class="container">
    <div class="row">
      <div class="col-xl-12">
        <div class="bradcam_text">
          <h3>{{jobs_count}}+ Jobs Available</h3>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="job_listing_area plus_padding">
  <div class="container">
    <div class="row">
      <div class="col-lg-3">
        <div class="job_filter white-bg">
          <div class="form_inner white-bg">
            <h3>Filter</h3>
            <form action="#">
              <div class="row">
                <div class="col-lg-12">
                  <div class="single_field">
                    <input type="text" placeholder="Search keyword" />
                  </div>
                </div>
              </div>
            </form>
          </div>
          <div class="search_btn">
            <button class="main-btn w-100" type="submit">Search</button>
          </div>
        </div>
      </div>
      <div class="col-lg-9">
        <div class="recent_joblist_wrap">
          <div class="recent_joblist white-bg">
            <div class="row align-items-center">
              <div class="col-md-6">
                <h4>Job Listing</h4>
              </div>
            </div>
          </div>
        </div>

        <div class="job_lists m-0">
          <div class="row">
            {% for job in jobs %}
            <div class="col-lg-12 col-md-12">
              <div class="single_jobs white-bg d-flex justify-content-between">
                <div class="jobs_left d-flex align-items-center">
                  <div class="thumb">
                    {% if job.job_image %}
                    <img src="{{job.job_image.url}}" alt="" width="70px" />
                    {% else %}
                    <img src="{% static 'images/default_img.png' %}" alt="" />
                    {% endif %}
                  </div>
                  <div class="jobs_conetent">
                    <a href="{% url 'jobs:job' job.id %}"><h4>{{job.job_title}}</h4></a>
                    <div class="links_locat d-flex align-items-center">
                      <div class="location">
                        <p><i class="fa fa-map-marker"></i> {{job.job_location}}</p>
                      </div>
                      <div class="location">
                        <p><i class="fa fa-clock-o"></i> {{job.job_type}}</p>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="jobs_right">
                  <div class="apply_now">
                    {% if user.is_superuser %}
                    <a href="{% url 'jobs:delete_job' job.id %}" class="delete-btn">Delete Now</a>
                    {% else %}
                    <a href="{% url 'jobs:job' job.id %}" class="main-btn">Apply Now</a>
                    {% endif %}
                  </div>
                  <div class="date">
                    <p>{{job.created_at}}</p>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
          {% if jobs.has_other_pages %}
          <div class="row">
            <div class="col-lg-12">
              <div class="pagination_wrap">
                <ul>
                  {% if jobs.has_previous %}
                  <li><a href="?page={{jobs.previous_page_number}}"> <i class="fa fa-angle-left"></i> </a></li>
                  {% endif %}

                  {% for i in jobs.paginator.page_range %}
                  <li><a href="?page={{i}}"><span>{{i}}</span></a></li>
                  {% endfor %}

                  {% if jobs.has_next %}
                  <li><a href="?page={{jobs.next_page_number}}"> <i class="fa fa-angle-right"></i> </a></li>
                  {% endif %}
                </ul>
              </div>
            </div>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Job Board</title>
    <!-- Icon Css Incloude-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" />
    <!-- Bootstrap CSS File -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <!-- Custom Css Include-->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
  <body>
    <!-- start header section -->
    <header>
      <div class="header-area">
        <div class="main-header-area">
          <div class="container-fluid">
            <div class="header_bottom_border">
              <div class="row align-items-center">
                <div class="col-xl-3 col-lg-2">
                  <div class="logo">
                    <a href="{% url 'jobs:jobs' %}">
                      <h3>Job-Board</h3>
                    </a>
                  </div>
                </div>
                <div class="col-xl-6 col-lg-7">
                  <div class="main-menu d-none d-lg-block">
                    <nav>
                      <ul id="navigation">
                        <li><a href="{% url 'jobs:jobs' %}">Home</a></li>
                        {% if user.is_superuser %}
                        <li><a href="{% url 'jobs:job_orders' %}">Job Orders</a></li>
                        <li><a href="{% url 'jobs:add_job' %}">Add Job</a></li>
                        <li><a href="{% url 'jobs:add_category' %}">Add Category</a></li>
                        {% endif %}
                      </ul>
                    </nav>
                  </div>
                </div>
                <div class="col-xl-3 col-lg-3 d-none d-lg-block">
                  <div class="Appointment">
                    <div class="phone_num d-none d-xl-block">
                      {% if user.is_authenticated %}
                      <a style="padding-right: 20px" href="{% url 'accounts:profile' %}">Profile</a>
                      <a class="main-btn" href="{% url 'logout' %}">Logout</a>
                      {% else %}
                      <a class="main-btn" href="{% url 'login' %}">Login</a>
                      {% endif %}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </header>
    <!-- end header section -->
    
    {% block content %}{% endblock content %}

    <!-- This Is All Plugins used-->
    <!-- JQuery Plugins include-->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <!-- Bootstrap 4 Plugins include-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
    <!-- Custom JQuery File-->
    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>